# alembic revision 파일(init): 실제 DB에 테이블을 만들고 삭제함
# Alembic가 자동 생성한 초기 스키마 생성(init) 마이그레이션 파일

"""init

Revision ID: d9c02b5b986d
Revises:
Create Date: 2026-02-19 11:26:55.595646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9c02b5b986d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 테이블 생성
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! “자동 생성”이므로 필요하면 사람이 조정하라는 의미 ###
    op.create_table(
        "artist_map",
        sa.Column("brikorea_name", sa.Text(), nullable=False),
        sa.Column("lastfm_artist_name", sa.Text(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("brikorea_name"),
    )
    op.create_table(
        "girl_group_rank",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_month", sa.Date(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("girl_group_name", sa.Text(), nullable=False),
        sa.Column("brand_score", sa.BigInteger(), nullable=False),
        sa.Column("activity_score", sa.BigInteger(), nullable=False),
        sa.Column("media_score", sa.BigInteger(), nullable=False),
        sa.Column("communication_score", sa.BigInteger(), nullable=False),
        sa.Column("community_score", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "snapshot_month", "girl_group_name", name="uq_snapshot_group"
        ),
    )
    op.create_table(
        "tracks",
        sa.Column("track_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("lastfm_artist_name", sa.Text(), nullable=False),
        sa.Column("track_name", sa.Text(), nullable=False),
        sa.Column("track_mbid", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("track_id"),
        sa.UniqueConstraint("lastfm_artist_name", "track_name", name="uq_artist_track"),
    )
    op.create_table(
        "track_listening_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("track_id", sa.BigInteger(), nullable=False),
        sa.Column("listeners_total", sa.BigInteger(), nullable=False),
        sa.Column("playcount_total", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["track_id"],
            ["tracks.track_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_date", "track_id", name="uq_snapshot_track"),
    )
    # ### end Alembic commands ###


# 테이블 삭제
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("track_listening_snapshot")
    op.drop_table("tracks")
    op.drop_table("girl_group_rank")
    op.drop_table("artist_map")
    # ### end Alembic commands ###
